"""Launch the MVP controller with a lightweight 2D closed-loop simulator."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    target_topic = LaunchConfiguration("target_topic")
    use_twist_stamped = LaunchConfiguration("use_twist_stamped")
    target_x = LaunchConfiguration("target_x")
    target_y = LaunchConfiguration("target_y")
    rviz = LaunchConfiguration("rviz")

    controller_config = PathJoinSubstitution([
        FindPackageShare("servo_control_pkg"),
        "config",
        "mvp_follow_controller.yaml",
    ])

    simple_robot_sim = Node(
        package="simulation_pkg",
        executable="simple_robot_sim_node.py",
        name="simple_robot_sim_node",
        output="screen",
        parameters=[{
            "target_topic": target_topic,
            "platform_state_topic": "/platform/state",
            "cmd_vel_topic": "/cmd_vel",
            "cmd_gimbal_topic": "/cmd_gimbal",
            "use_twist_stamped": ParameterValue(use_twist_stamped, value_type=bool),
            "image_width": 640,
            "image_height": 480,
            "desired_distance": 2.0,
            "target_x": ParameterValue(target_x, value_type=float),
            "target_y": ParameterValue(target_y, value_type=float),
        }],
    )

    mvp_controller = Node(
        package="servo_control_pkg",
        executable="mvp_follow_controller_node",
        name="mvp_follow_controller_node",
        output="screen",
        parameters=[
            controller_config,
            {
                "target_topic": target_topic,
                "platform_state_topic": "/platform/state",
                "use_twist_stamped": ParameterValue(use_twist_stamped, value_type=bool),
                "use_mock_gimbal_state": False,
            },
        ],
    )

    rviz_node = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        condition=IfCondition(rviz),
    )

    return LaunchDescription([
        DeclareLaunchArgument(
            "target_topic",
            default_value="/target/current",
            description="TargetArray topic generated by the simple 2D simulator.",
        ),
        DeclareLaunchArgument(
            "use_twist_stamped",
            default_value="true",
            description="Use TwistStamped for /cmd_vel when true, Twist when false.",
        ),
        DeclareLaunchArgument(
            "target_x",
            default_value="3.0",
            description="Target x position in odom frame.",
        ),
        DeclareLaunchArgument(
            "target_y",
            default_value="1.0",
            description="Target y position in odom frame; positive starts to robot left.",
        ),
        DeclareLaunchArgument(
            "rviz",
            default_value="false",
            description="Start RViz2 with default config.",
        ),
        simple_robot_sim,
        mvp_controller,
        rviz_node,
    ])
